export enum EntityName{
User="user",
Category="category",
Address="address",
UserOtp="user_otp",
supplierOtp="supplier_otp",
Supplier="supplier",
Menu="menu",
Feedback="feedback",
MenuType="menu_type",
Discount="discount",
UserBasket="user_basket",
Order="order",
OrderItems="order_items",
Payment="payment",
}      